### ISSUE TITLE
Could you attach versions of each nodejs lib?

### ISSUE THREAD

**Issue by FinalTheory** [ppwwyyxx/duxiu-downloader#2]
Error on my machine(Fedora 20, nodejs v0.10.36, request@2.54.0, mime@1.3.4, CoffeeScript version 1.9.1):

TypeError: Cannot read property 'headers' of undefined
  at Request._callback (/home/god/duxiu/duxiu-downloader/duxiu.coffee:86:5)
  at self.callback (/home/god/duxiu/duxiu-downloader/node_modules/request/request.js:360:22)
  at Request.emit (events.js:95:17)
  at Request.onRequestError (/home/god/duxiu/duxiu-downloader/node_modules/request/request.js:1008:8)
  at ClientRequest.emit (events.js:95:17)
  at Socket.socketErrorListener (http.js:1552:9)
  at Socket.emit (events.js:95:17)
  at net.js:834:16
  at process._tickCallback (node.js:442:13)

**Comment by ppwwyyxx** [comment]
Oh. I stop updating that js version a long time ago. 
The last time I use this downloader, the python version works fine. I'm not sure whether it works now because the protocols may change. But you can give that a try.

**Comment by FinalTheory** [comment]
Seems the protocol has changed, thx
